// @title Cart Service
// @version 1.0
// @description This is a sample  Cart service
// @termsOfService http://swagger.io/terms/
// @contact.name API Support
// @contact.email vishnu@swagger.io
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @host localhost:7676
// @BasePath /
package main

import (
	_ "Case-Study/Cart-Service/docs" // docs is generated by Swag CLI, you have to import it.
	"Case-Study/Cart-Service/interfaces"
	"Case-Study/Cart-Service/lib/database"
	"Case-Study/Cart-Service/model"
	api "Case-Study/Cart-Service/reciever"
	"log"
	"net/http"

	httpSwagger "github.com/swaggo/http-swagger"

	"github.com/gorilla/mux"
)

func main() {
	err := initDBClient()
	if err != nil {
		log.Fatal("DB Driver error", err)
	}

	router := mux.NewRouter()

	router.HandleFunc("/cart", api.Update.InsertProductHandler).Methods("PUT")
	router.HandleFunc("/cart", api.Get.GetCartHandler).Methods("GET")
	router.HandleFunc("/cart/updateQuantity/{productID}", api.Update.UpdateQuantityHandler).Methods("PUT")
	router.HandleFunc("/cart/{productID}", api.Delete.DeleteProductHandler).Methods("DELETE")
	log.Println("Starting the application at port 7676")
	router.PathPrefix("/swagger").Handler(httpSwagger.WrapHandler)
	http.ListenAndServe(":7676", router)
}

func initDBClient() error {
	var config model.DBConfig
	config.User = "vishnu95"
	config.Password = "admin123"
	config.Port = 27017
	config.Host = "cluster0.3ifgh.mongodb.net"
	interfaces.DBClient = new(database.DBRepo)
	err := interfaces.DBClient.DBConnect(config)
	return err
}
