basePath: /
host: localhost:7676
info:
  contact:
    email: vishnu@swagger.io
    name: API Support
  description: This is a sample  Cart service
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Cart Service
  version: "1.0"
paths: {}
swagger: "2.0"
